name: Code quality
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.js'
      - 'biome.json'
jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 23
    - name: Install packages
      run: npm clean-install --include dev --no-audit --no-fund
    - name: Run Biome check
      run: npm run check || exit 1